main: com.keaton.jsonissavage.Main
name: JSONPlayerCount
version: 1.1
author: me
description: Outputs player count to json.
commands:
  mycommand:
    description: Displays playercount
    usage: /playercount
    permission: jsoncount.count
    permission-message: You don't have the jsoncount.count permission.